// src/styles/theme.ts
export const theme = {
  colors: {
    textWhite: "#f8f9fa",
    textDarkNavy: "#0a1f44",
    textDarkBlue: "#162e5c",
    textOrange: "#c87533",
    textBrightBrown: "#a14d26",
    textChickenComb: "#db2323",
    bgWhite: "#f8f9fa",
    bgLightGray: "#d3d3d3",
    bgDarkGray: "#a9a9a9",
    bgRichPewter: "#6a6f70",
    bgDarkNavy: "#0a1f44",
    bgJacarandaLight: "#a7acb9",
    bgCrowBlack: "#263348",
    bgOrange: "#c87533",
    bgBrightBrown: "#a14d26",
    colGrannySmith: "#7c9c9a",
    colPickledBluewood: "#253943",
    colMilkPunch: "#fff5d6 ",
    colTallow: "#a8a28a",
    colTeak: "#b38b6d",
    colAvocado: "#8f9b69",

    colIndianRed: "#CD5C5C",
    colLightCoral: "#F08080",
    colSalmon: "#FA8072",
    colDarkSalmon: "#E9967A",
    colLightSalmon: "#FFA07A",
    colCrimson: "#DC143C",
    colRed: "#FF0000",
    colFireBrick: "#B22222",
    colDarkRed: "#8B0000",

    colPink: "#FFC0CB",
    colLightPink: "#FFB6C1",
    colHotPink: "#FF69B4",
    colDeepPink: "#FF1493",
    colMediumVioletRed: "#C71585",
    colPaleVioletRed: "#DB7093",

    colCoral: "#FF7F50",
    colTomato: "#FF6347",
    colOrangeRed: "#FF4500",
    colDarkOrange: "#FF8C00",
    colOrange: "#FFA500",

    colGold: "#FFD700",
    colYellow: "#FFFF00",
    colLightYellow: "#FFFFE0",
    colLemonChiffon: "#FFFACD",
    colLightGoldenrodYellow: "#FAFAD2",
    colPapayaWhip: "#FFEFD5",
    colMoccasin: "#FFE4B5",
    colPeachPuff: "#FFDAB9",
    colPaleGoldenrod: "#EEE8AA",
    colKhaki: "#F0E68C",
    colDarkKhaki: "#BDB76B",

    colLavender: "#E6E6FA",
    colThistle: "#D8BFD8",
    colPlum: "#DDA0DD",
    colViolet: "#EE82EE",
    colOrchid: "#DA70D6",
    colFuchsia: "#FF00FF",
    colMagenta: "#FF00FF",
    colMediumOrchid: "#BA55D3",
    colMediumPurple: "#9370DB",
    colRebeccaPurple: "#663399",
    colBlueViolet: "#8A2BE2",
    colDarkViolet: "#9400D3",
    colDarkOrchid: "#9932CC",
    colDarkMagenta: "#8B008B",
    colPurple: "#800080",
    colIndigo: "#4B0082",
    colSlateBlue: "#6A5ACD",
    colDarkSlateBlue: "#483D8B",
    colMediumSlateBlue: "#7B68EE",

    colGreenYellow: "#ADFF2F",
    colChartreuse: "#7FFF00",
    colLawnGreen: "#7CFC00",
    colLime: "#00FF00",
    colLimeGreen: "#32CD32",
    colPaleGreen: "#98FB98",
    colLightGreen: "#90EE90",
    colMediumSpringGreen: "#00FA9A",
    colSpringGreen: "#00FF7F",
    colMediumSeaGreen: "#3CB371",
    colSeaGreen: "#2E8B57",
    colForestGreen: "#228B22",
    colGreen: "#008000",
    colDarkGreen: "#006400",
    colYellowGreen: "#9ACD32",
    colOliveDrab: "#6B8E23",
    colOlive: "#808000",
    colDarkOliveGreen: "#556B2F",
    colMediumAquamarine: "#66CDAA",
    colDarkSeaGreen: "#8FBC8B",
    colLightSeaGreen: "#20B2AA",
    colDarkCyan: "#008B8B",
    colTeal: "#008080",

    colCyan: "#00FFFF",
    colLightCyan: "#E0FFFF",
    colPaleTurquoise: "#AFEEEE",
    colAquamarine: "#7FFFD4",
    colTurquoise: "#40E0D0",
    colMediumTurquoise: "#48D1CC",
    colDarkTurquoise: "#00CED1",
    colCadetBlue: "#5F9EA0",
    colSteelBlue: "#4682B4",
    colLightSteelBlue: "#B0C4DE",
    colPowderBlue: "#B0E0E6",
    colLightBlue: "#ADD8E6",
    colSkyBlue: "#87CEEB",
    colLightSkyBlue: "#87CEFA",
    colDeepSkyBlue: "#00BFFF",
    colDodgerBlue: "#1E90FF",
    colCornflowerBlue: "#6495ED",
    colRoyalBlue: "#4169E1",
    colBlue: "#0000FF",
    colMediumBlue: "#0000CD",
    colDarkBlue: "#00008B",
    colNavy: "#000080",
    colMidnightBlue: "#191970",

    colCornsilk: "#FFF8DC",
    colBlanchedAlmond: "#FFEBCD",
    colBisque: "#FFE4C4",
    colNavajoWhite: "#FFDEAD",
    colWheat: "#F5DEB3",
    colBurlyWood: "#DEB887",
    colTan: "#D2B48C",
    colRosyBrown: "#BC8F8F",
    colSandyBrown: "#F4A460",
    colGoldenrod: "#DAA520",
    colDarkGoldenrod: "#B8860B",
    colPeru: "#CD853F",
    colChocolate: "#D2691E",
    colSaddleBrown: "#8B4513",
    colSienna: "#A0522D",
    colBrown: "#A52A2A",
    colMaroon: "#800000",

    colWhite: "#FFFFFF",
    colSnow: "#FFFAFA",
    colHoneyDew: "#F0FFF0",
    colMintCream: "#F5FFFA",
    colAzure: "#F0FFFF",
    colAliceBlue: "#F0F8FF",
    colGhostWhite: "#F8F8FF",
    colWhiteSmoke: "#F5F5F5",
    colSeaShell: "#FFF5EE",
    colBeige: "#F5F5DC",
    colOldLace: "#FDF5E6",
    colFloralWhite: "#FFFAF0",
    colIvory: "#FFFFF0",
    colAntiqueWhite: "#FAEBD7",
    colLinen: "#FAF0E6",
    colLavenderBlush: "#FFF0F5",
    colMistyRose: "#FFE4E1",

    colGainsboro: "#DCDCDC",
    colLightGray: "#D3D3D3",
    colSilver: "#C0C0C0",
    colDarkGray: "#A9A9A9",
    colGray: "#808080",
    colDimGray: "#696969",
    colLightSlateGray: "#778899",
    colSlateGray: "#708090",
    colDarkSlateGray: "#2F4F4F",
    colBlack: "#000000",
  },

  headerHeight: "130px",

  breakpoints: {
    mobile: "768px",
    tablet: "1200px",
    desktop: "1440px",
  },
  media: {
    mobile: `(max-width: 767px)`,
    tablet: `(min-width: 768px) and (max-width: 1199px)`,
    desktop: `(min-width: 1200px)`,
    mobileAndTablet: `(max-width: 1199px)`,
    tabletAndDesktop: `(min-width: 768px)`,
  },
  spacing: {
    mobilePadding: "5px",
    tabletPadding: "10px",
    desktopPadding: "0px",
  },
};

export const lightTheme = {
  ...theme,
  colors: {
    ...theme.colors,
    bgPrimary: theme.colors.colMilkPunch,
    bgSecondary: theme.colors.colSienna,
    textPrimary: theme.colors.colPickledBluewood,
    textSecondary: theme.colors.colMilkPunch,
    accent: theme.colors.colGrannySmith,
    hover: theme.colors.colGrannySmith,
    hoverButton: theme.colors.colAvocado,
    distinction: theme.colors.colGrannySmith,
  },
};

export const darkTheme = {
  ...theme,
  colors: {
    ...theme.colors,
    bgPrimary: theme.colors.colPickledBluewood,
    bgSecondary: theme.colors.colPickledBluewood,
    textPrimary: theme.colors.colMilkPunch,
    textSecondary: theme.colors.colMilkPunch,
    accent: theme.colors.colTeak,
    hover: theme.colors.colTallow,
    hoverButton: theme.colors.colAvocado,
    distinction: theme.colors.colGrannySmith,
  },
};
